# Parameters related to building hip
ARG base_image

FROM ${base_image}
LABEL maintainer="akila.premachandra@amd.com"

ARG user_uid

RUN yum -y update && yum install -y \
    sudo \
    rocm* \
    rocfft \
    centos-release-scl \
    devtoolset-7 \
    ca-certificates \
    git \
    cmake3 \
    make \
    clang \
    clang-devel \
    gcc-c++ \
    gcc-gfortran \
    fftw-devel \
    pkgconfig \
    python27 \
    python34 \
    PyYAML \
    libcxx-devel \
    boost-devel\
    numactl-libs \
    rpm-build \
    && \
    yum -y clean all 

RUN scl enable devtoolset-7 bash

# docker pipeline runs containers with particular uid
# create a jenkins user with this specific uid so it can use sudo priviledges
# Grant any member of sudo group password-less sudo privileges
RUN useradd --create-home -u ${user_uid} -o -G wheel --shell /bin/bash jenkins && \
    echo '%wheel   ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers